import Head from 'next/head'
import AvailableSliderSection from './home/AvailableSlider';
import HeroSection from './home/HeroSection';
import MakeMoneySection from './home/MakeMoneySection';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeroSection />
      <AvailableSliderSection />
      <MakeMoneySection />
    </div>
  );
}
